Expired beacons fix.
CCExtractor/beacon pull request #33
Opened 2021-12-27 20:32 UTC by Aadeesh11

Expected Behaviour: 

- [X] Show expired beacons at the very last in your beacons section.
- [X] Cancel subs (if subs have already been setup) and not setup them up (if user opens an expired  beacon).
- [X] Show snackBar if user tries to join expired beacon.
- [ ] Stop user from joining expired beacon.

2021-12-27 20:37 UTC, Aadeesh11 commented
Should the last(4th) be part of backend logic or frontend? Because if it is a part of frontend logic, then while joining we would need an extra network call to get beacon data(since we only know shortcode at the time of joining).
@nb9960  please let me know on how to proceed from here.

2021-12-28 10:00 UTC, cfsmp3 commented
> Should the last(5th) be part of backend logic or frontend? 

Anything related to security / privacy / etc must be handled in the backend - you just can't trust the frontend :-)

So the backend should prevent joining an expired beacon, return some error, and then the frontend can capture that error and display it.

2021-12-28 10:12 UTC, Aadeesh11 commented
> > Should the last(5th) be part of backend logic or frontend?
> 
> Anything related to security / privacy / etc must be handled in the backend - you just can't trust the frontend :-)
> 
> So the backend should prevent joining an expired beacon, return some error, and then the frontend can capture that error and display it.

Ok understood, would create a new issue regarding this in the beacon-backend repository.

2021-12-28 12:50 UTC, Aadeesh11 commented
CI would pass once #42 gets merged.

2021-12-29 19:09 UTC, nb9960 requested changes

2021-12-29 19:09 UTC, nb9960 commented on lib/views/hike_screen.dart
> +        mergeStreamSubscription.cancel();
```suggestion
        mergeStreamSubscription.cancel();
        setState(() {
          isBeaconExpired = true;
        });
```

2021-12-29 19:17 UTC, nb9960 commented
Also, can you change the beacon exit dialog when the beacon has expired? Currently, the message is: 'There are ${X - 1} followers and you are carrying the beacon. Do you want to terminate the hike?'. Change it to 'Are you sure you want to exit? or something similar' **if** beacon has expired.

2021-12-29 20:14 UTC, Aadeesh11 commented
> Also, can you change the beacon exit dialog when the beacon has expired? Currently, the message is: 'There are ${X - 1} followers and you are carrying the beacon. Do you want to terminate the hike?'. Change it to 'Are you sure you want to exit? or something similar' **if** beacon has expired.

Would change that too.

2021-12-30 08:42 UTC, nb9960 approved these changes

2021-12-30 08:45 UTC, merged

2021-12-30 08:45 UTC, nb9960 commented
Thanks for the PR, merged! :tada: