Updated UI, fixed bugs and refactored code
CCExtractor/beacon pull request #45
Opened 2021-12-28 19:22 UTC by ItsAdityaKSingh

## This PR fixes issues:
- #22 
- #23 
- #25 
- #32 

Along with the **UI improvements** and minor **bug** fixes, I have minutely **refactored** the code for proper readability and understanding, added **commas(,)** at a few places, fixed **sizing issues** for all the containers and buttons, and also tried to improve the **overall interface**. Any suggestions for improvements are most welcome!

2021-12-29 14:20 UTC, ItsAdityaKSingh commented
Fixed the issue #44  here itself

2021-12-29 18:01 UTC, nb9960 requested changes

2021-12-29 19:40 UTC, ItsAdityaKSingh commented on lib/components/create_join_dialog.dart
> +                          },
Yes, my bad, they were changed while removing some of my bug-fixing commits earlier😅. I have fixed them! Really sorry for the trouble caused.

2022-01-09 12:36 UTC, nb9960 commented
Hey @ItsAdityaKSingh, This PR still doesn't reflect the desired changes. In fact, UI had no issues earlier, but now it has (adding the screenshot below for reference). Maybe run gh pr checkout 45 or make sure you've pulled the changes locally and then try to test your changes.
![Screenshot_20220109-165337.jpg](https://user-images.githubusercontent.com/63557873/148682415-a85a6405-3514-4a71-8c45-110098dba070.jpg)

2022-01-09 12:41 UTC, nb9960 reviewed
Hey @ItsAdityaKSingh, This PR still doesn't reflect the desired changes. In fact, UI had no issues earlier, but now it has (adding the screenshot below for reference). Maybe run gh pr checkout 45 or make sure you've pulled the changes locally and then try to test your changes.
<img src="https://user-images.githubusercontent.com/63557873/148682415-a85a6405-3514-4a71-8c45-110098dba070.jpg" width="250" height="500">

2022-01-12 14:16 UTC, nb9960 approved these changes

2022-01-12 14:16 UTC, merged

2022-01-12 14:17 UTC, nb9960 commented
Thanks for the PR @ItsAdityaKSingh , Merged! :tada: